### ISSUE TITLE
Enable memory manager tests

### ISSUE THREAD

**Issue by boramalper** [ease-lab/vhive#270] opened 2021-06-07 14:22 UTC
`memory/manager/manager_test.go` exists but all tests are commented out.

- [ ] Why they have been commented out?
- [ ] How to enable them?

See https://github.com/ease-lab/vhive/pull/268#discussion_r646628346

**Comment by ustiugov** [comment] 2021-06-07 14:36
Duplicate of #36. sorry.

**Closed by ustiugov** 2021-06-07 14:36 UTC
Labels: bug
