### ISSUE TITLE
go build failed

### ISSUE THREAD

**Issue by lolo-pop** [ease-lab/vhive#543] opened 2022-05-31 07:56 UTC
**Describe the bug**
I am trying to build the vhive environment based on "[Setup a Single-Node Cluster](https://github.com/ease-lab/vhive/blob/main/docs/quickstart_guide.md#iii-setup-a-single-node-cluster)". I get an error "unknown revision 6af02db30bc4" when I download the package "github.com/ease-lab/firecracker-containerd@v0.0.0-20210618165033-6af02db30bc4". All other go packages can be downloaded normally.

**To Reproduce**
`source /etc/profile && go build;`
`go: github.com/firecracker-microvm/firecracker-containerd@v0.0.0-00010101000000-000000000000 (replaced by github.com/ease-lab/firecracker-containerd@v0.0.0-20210618165033-6af02db30bc4): version "v0.0.0-20210618165033-6af02db30bc4" invalid: unknown revision 6af02db30bc4`
`go: downloading github.com/ease-lab/firecracker-containerd v0.0.0-20210618165033-6af02db30bc4`
`go: github.com/firecracker-microvm/firecracker-containerd@v0.0.0-00010101000000-000000000000 (replaced by github.com/ease-lab/firecracker-containerd@v0.0.0-20210618165033-6af02db30bc4): version "v0.0.0-20210618165033-6af02db30bc4" invalid: unknown revision 6af02db30bc4
`

**Expected behavior**
I would like to know how to solve this problem, looking forward to your reply.

**Comment by ustiugov** [comment] 2022-06-03 16:25
@lolo-pop thank you for reporting the issue. I cannot reproduce this issue in our CI [run](https://github.com/ease-lab/vhive/runs/6729088795?check_suite_focus=true), which indicates that your Golang installation might got corrupted. Try reinstalling Go.

**Comment by ustiugov** [comment] 2022-08-17 08:25
Closing it as there hasn't been any activity.

**Closed by ustiugov** 2022-08-17 08:25 UTC
Labels: bug, wontfix
